### ISSUE TITLE
新版回复中断问题

### ISSUE THREAD

**Issue by irol765** [gptlink/gptlink#61]
[2023-07-15 21:00:35 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#8 does not exists
[2023-07-15 21:00:35 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#5 does not exists
[2023-07-15 21:00:35 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#4 does not exists
[2023-07-15 21:00:35 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#2 does not exists
[2023-07-15 21:00:35 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#1 does not exists
[2023-07-15 21:00:36 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#9 does not exists
[2023-07-15 21:00:50 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#10 does not exists
[2023-07-15 21:01:02 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#11 does not exists
[2023-07-15 21:01:03 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#12 does not exists
[2023-07-15 21:01:28 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#13 does not exists
[2023-07-15 21:01:40 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#14 does not exists
[2023-07-15 21:02:01 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#15 does not exists
[2023-07-15 21:02:15 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#16 does not exists
[2023-07-15 21:02:31 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#18 does not exists
[2023-07-15 21:02:31 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#19 does not exists
[2023-07-15 21:02:31 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#20 does not exists
[2023-07-15 21:02:31 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#21 does not exists
[2023-07-15 21:02:31 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#22 does not exists
[2023-07-15 21:02:31 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#23 does not exists
[2023-07-15 21:02:31 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#24 does not exists
[2023-07-15 21:02:31 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#17 does not exists
[2023-07-15 21:02:32 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#25 does not exists
[2023-07-15 21:02:35 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#26 does not exists
[2023-07-15 21:02:40 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#27 does not exists
[2023-07-15 21:02:52 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#28 does not exists
[2023-07-15 21:03:03 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#29 does not exists
[2023-07-15 21:03:07 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#34 does not exists
[2023-07-15 21:03:07 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#36 does not exists
[2023-07-15 21:03:07 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#33 does not exists
[2023-07-15 21:03:07 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#32 does not exists
[2023-07-15 21:03:07 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#31 does not exists
[2023-07-15 21:03:07 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#35 does not exists
[2023-07-15 21:03:07 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#37 does not exists
[2023-07-15 21:03:07 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#30 does not exists
[2023-07-15 21:03:08 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#38 does not exists
[2023-07-15 21:03:13 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#39 does not exists
[2023-07-15 21:03:16 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#40 does not exists
[2023-07-15 21:03:25 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#41 does not exists
[2023-07-15 21:03:33 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#43 does not exists
[2023-07-15 21:03:33 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#44 does not exists
[2023-07-15 21:03:33 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#45 does not exists
[2023-07-15 21:03:33 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#46 does not exists
[2023-07-15 21:03:33 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#47 does not exists
[2023-07-15 21:03:33 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#48 does not exists
[2023-07-15 21:03:33 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#49 does not exists
[2023-07-15 21:03:34 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#42 does not exists
[2023-07-15 21:03:34 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#50 does not exists
[2023-07-15 21:03:52 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#51 does not exists
[2023-07-15 21:07:17 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#52 does not exists
[2023-07-15 21:21:37 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#55 does not exists
[2023-07-15 21:21:37 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#54 does not exists
[2023-07-15 21:21:37 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#56 does not exists
[2023-07-15 21:21:37 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#58 does not exists
[2023-07-15 21:21:37 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#57 does not exists
[2023-07-15 21:21:37 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#59 does not exists
[2023-07-15 21:21:37 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#60 does not exists
[2023-07-15 21:21:37 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#53 does not exists
[2023-07-15 21:21:38 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#61 does not exists
[2023-07-15 21:21:41 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#62 does not exists
[2023-07-15 21:21:41 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#63 does not exists
[2023-07-15 21:21:58 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#64 does not exists
[2023-07-15 21:24:10 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#65 does not exists
[2023-07-15 21:24:27 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#66 does not exists
[2023-07-15 21:24:36 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#67 does not exists
[2023-07-15 21:25:16 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#68 does not exists
[2023-07-15 21:27:03 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#69 does not exists
[2023-07-15 21:39:10 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#71 does not exists
[2023-07-15 21:39:10 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#72 does not exists
[2023-07-15 21:39:10 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#73 does not exists
[2023-07-15 21:39:10 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#74 does not exists
[2023-07-15 21:39:10 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#70 does not exists
[2023-07-15 21:39:23 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#78 does not exists
[2023-07-15 21:39:23 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#77 does not exists
[2023-07-15 21:39:23 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#76 does not exists
[2023-07-15 21:39:23 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#79 does not exists
[2023-07-15 21:39:24 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#75 does not exists
[2023-07-15 21:39:27 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#80 does not exists
[2023-07-15 21:39:27 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#81 does not exists
[2023-07-15 21:39:27 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#82 does not exists
[2023-07-15 21:39:35 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#83 does not exists
[2023-07-15 21:39:35 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#85 does not exists
[2023-07-15 21:39:35 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#86 does not exists
[2023-07-15 21:39:35 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#87 does not exists
[2023-07-15 21:39:35 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#88 does not exists
[2023-07-15 21:39:35 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#89 does not exists
[2023-07-15 21:39:35 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#90 does not exists
[2023-07-15 21:39:35 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#91 does not exists
[2023-07-15 21:39:35 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#84 does not exists
[2023-07-15 21:39:36 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#92 does not exists
[2023-07-15 21:40:09 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#93 does not exists
bash: cannot set terminal process group (-1): Not a tty
bash: no job control in this shell
Nothing to migrate.
[INFO] Process[queue.default.0] start.
[INFO] Process[crontab-dispatcher.0] start.
[INFO] Process[queue.default.0] start.
[INFO] Worker#0 started.
[INFO] HTTP Server listening at 0.0.0.0:9503
[2023-07-15 21:44:31 *26.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#1 does not exists
[INFO] Crontab task [memberPackageExpired] executed successfully at 2023-07-15 22:00:00.

**Comment by 0daynick** [comment]
可能是你 redis 不太稳定

**Comment by irol765** [comment]
我重建了，一样的

**Comment by irol765** [comment]
1:C 16 Jul 2023 15:35:49.660 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 16 Jul 2023 15:35:49.660 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 16 Jul 2023 15:35:49.660 # Configuration loaded
1:M 16 Jul 2023 15:35:49.661 * monotonic clock: POSIX clock_gettime
1:M 16 Jul 2023 15:35:49.662 * Running mode=standalone, port=6379.
1:M 16 Jul 2023 15:35:49.662 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 16 Jul 2023 15:35:49.662 # Server initialized
1:M 16 Jul 2023 15:35:49.662 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 16 Jul 2023 15:35:49.662 * Loading RDB produced by version 7.0.11
1:M 16 Jul 2023 15:35:49.662 * RDB age 1 seconds
1:M 16 Jul 2023 15:35:49.662 * RDB memory usage when created 3.69 Mb
1:M 16 Jul 2023 15:35:49.667 * Done loading RDB, keys loaded: 33, keys expired: 0.
1:M 16 Jul 2023 15:35:49.668 * DB loaded from disk: 0.005 seconds
1:M 16 Jul 2023 15:35:49.668 * Ready to accept connections

**Comment by irol765** [comment]
[ERROR] RedisException: Connection refused in /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php:268

Stack trace:
#0 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(268): Redis->connect()
#1 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(117): Hyperf\Redis\RedisConnection->createRedis()
#2 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(91): Hyperf\Redis\RedisConnection->reconnect()
#3 /app/gptserver/vendor/hyperf/pool/src/Connection.php(54): Hyperf\Redis\RedisConnection->getActiveConnection()
#4 /app/gptserver/vendor/hyperf/redis/src/Redis.php(47): Hyperf\Pool\Connection->getConnection()
#5 /app/gptserver/vendor/hyperf/redis/src/RedisProxy.php(32): Hyperf\Redis\Redis->__call()
#6 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(193): Hyperf\Redis\RedisProxy->__call()
#7 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(85): Hyperf\AsyncQueue\Driver\RedisDriver->move()
#8 /app/gptserver/vendor/hyperf/async-queue/src/Driver/Driver.php(86): Hyperf\AsyncQueue\Driver\RedisDriver->pop()
#9 /app/gptserver/vendor/hyperf/async-queue/src/Process/ConsumerProcess.php(57): Hyperf\AsyncQueue\Driver\Driver->consume()
#10 /app/gptserver/vendor/hyperf/process/src/AbstractProcess.php(134): Hyperf\AsyncQueue\Process\ConsumerProcess->handle()
#11 {main}
[ERROR] RedisException: Connection refused in /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php:268

Stack trace:
#0 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(268): Redis->connect()
#1 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(117): Hyperf\Redis\RedisConnection->createRedis()
#2 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(91): Hyperf\Redis\RedisConnection->reconnect()
#3 /app/gptserver/vendor/hyperf/pool/src/Connection.php(54): Hyperf\Redis\RedisConnection->getActiveConnection()
#4 /app/gptserver/vendor/hyperf/redis/src/Redis.php(47): Hyperf\Pool\Connection->getConnection()
#5 /app/gptserver/vendor/hyperf/redis/src/RedisProxy.php(32): Hyperf\Redis\Redis->__call()
#6 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(193): Hyperf\Redis\RedisProxy->__call()
#7 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(85): Hyperf\AsyncQueue\Driver\RedisDriver->move()
#8 /app/gptserver/vendor/hyperf/async-queue/src/Driver/Driver.php(86): Hyperf\AsyncQueue\Driver\RedisDriver->pop()
#9 /app/gptserver/vendor/hyperf/async-queue/src/Process/ConsumerProcess.php(57): Hyperf\AsyncQueue\Driver\Driver->consume()
#10 /app/gptserver/vendor/hyperf/process/src/AbstractProcess.php(134): Hyperf\AsyncQueue\Process\ConsumerProcess->handle()
#11 {main}
[WARNING] Get connection failed, try again. RedisException: Connection refused in /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php:268

Stack trace:
#0 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(268): Redis->connect()
#1 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(117): Hyperf\Redis\RedisConnection->createRedis()
#2 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(91): Hyperf\Redis\RedisConnection->reconnect()
#3 /app/gptserver/vendor/hyperf/pool/src/Connection.php(49): Hyperf\Redis\RedisConnection->getActiveConnection()
#4 /app/gptserver/vendor/hyperf/redis/src/Redis.php(47): Hyperf\Pool\Connection->getConnection()
#5 /app/gptserver/vendor/hyperf/redis/src/RedisProxy.php(32): Hyperf\Redis\Redis->__call()
#6 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(193): Hyperf\Redis\RedisProxy->__call()
#7 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(85): Hyperf\AsyncQueue\Driver\RedisDriver->move()
#8 /app/gptserver/vendor/hyperf/async-queue/src/Driver/Driver.php(86): Hyperf\AsyncQueue\Driver\RedisDriver->pop()
#9 /app/gptserver/vendor/hyperf/async-queue/src/Process/ConsumerProcess.php(57): Hyperf\AsyncQueue\Driver\Driver->consume()
#10 /app/gptserver/vendor/hyperf/process/src/AbstractProcess.php(134): Hyperf\AsyncQueue\Process\ConsumerProcess->handle()
#11 {main}
[WARNING] Get connection failed, try again. RedisException: Connection refused in /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php:268

Stack trace:
#0 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(268): Redis->connect()
#1 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(117): Hyperf\Redis\RedisConnection->createRedis()
#2 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(91): Hyperf\Redis\RedisConnection->reconnect()
#3 /app/gptserver/vendor/hyperf/pool/src/Connection.php(49): Hyperf\Redis\RedisConnection->getActiveConnection()
#4 /app/gptserver/vendor/hyperf/redis/src/Redis.php(47): Hyperf\Pool\Connection->getConnection()
#5 /app/gptserver/vendor/hyperf/redis/src/RedisProxy.php(32): Hyperf\Redis\Redis->__call()
#6 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(193): Hyperf\Redis\RedisProxy->__call()
#7 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(85): Hyperf\AsyncQueue\Driver\RedisDriver->move()
#8 /app/gptserver/vendor/hyperf/async-queue/src/Driver/Driver.php(86): Hyperf\AsyncQueue\Driver\RedisDriver->pop()
#9 /app/gptserver/vendor/hyperf/async-queue/src/Process/ConsumerProcess.php(57): Hyperf\AsyncQueue\Driver\Driver->consume()
#10 /app/gptserver/vendor/hyperf/process/src/AbstractProcess.php(134): Hyperf\AsyncQueue\Process\ConsumerProcess->handle()
#11 {main}
[ERROR] RedisException: Connection refused in /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php:268

Stack trace:
#0 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(268): Redis->connect()
#1 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(117): Hyperf\Redis\RedisConnection->createRedis()
#2 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(91): Hyperf\Redis\RedisConnection->reconnect()
#3 /app/gptserver/vendor/hyperf/pool/src/Connection.php(54): Hyperf\Redis\RedisConnection->getActiveConnection()
#4 /app/gptserver/vendor/hyperf/redis/src/Redis.php(47): Hyperf\Pool\Connection->getConnection()
#5 /app/gptserver/vendor/hyperf/redis/src/RedisProxy.php(32): Hyperf\Redis\Redis->__call()
#6 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(193): Hyperf\Redis\RedisProxy->__call()
#7 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(85): Hyperf\AsyncQueue\Driver\RedisDriver->move()
#8 /app/gptserver/vendor/hyperf/async-queue/src/Driver/Driver.php(86): Hyperf\AsyncQueue\Driver\RedisDriver->pop()
#9 /app/gptserver/vendor/hyperf/async-queue/src/Process/ConsumerProcess.php(57): Hyperf\AsyncQueue\Driver\Driver->consume()
#10 /app/gptserver/vendor/hyperf/process/src/AbstractProcess.php(134): Hyperf\AsyncQueue\Process\ConsumerProcess->handle()
#11 {main}
[ERROR] RedisException: Connection refused in /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php:268

Stack trace:
#0 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(268): Redis->connect()
#1 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(117): Hyperf\Redis\RedisConnection->createRedis()
#2 /app/gptserver/vendor/hyperf/redis/src/RedisConnection.php(91): Hyperf\Redis\RedisConnection->reconnect()
#3 /app/gptserver/vendor/hyperf/pool/src/Connection.php(54): Hyperf\Redis\RedisConnection->getActiveConnection()
#4 /app/gptserver/vendor/hyperf/redis/src/Redis.php(47): Hyperf\Pool\Connection->getConnection()
#5 /app/gptserver/vendor/hyperf/redis/src/RedisProxy.php(32): Hyperf\Redis\Redis->__call()
#6 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(193): Hyperf\Redis\RedisProxy->__call()
#7 /app/gptserver/vendor/hyperf/async-queue/src/Driver/RedisDriver.php(85): Hyperf\AsyncQueue\Driver\RedisDriver->move()
#8 /app/gptserver/vendor/hyperf/async-queue/src/Driver/Driver.php(86): Hyperf\AsyncQueue\Driver\RedisDriver->pop()
#9 /app/gptserver/vendor/hyperf/async-queue/src/Process/ConsumerProcess.php(57): Hyperf\AsyncQueue\Driver\Driver->consume()
#10 /app/gptserver/vendor/hyperf/process/src/AbstractProcess.php(134): Hyperf\AsyncQueue\Process\ConsumerProcess->handle()
#11 {main}
[2023-07-17 00:27:51 *28.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#76 does not exists
[2023-07-17 00:28:06 *28.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#77 does not exists
[2023-07-17 00:28:40 *28.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#78 does not exists
[2023-07-17 00:28:48 *28.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#79 does not exists
[2023-07-17 00:28:51 *28.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#80 does not exists
[2023-07-17 00:28:51 *28.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#81 does not exists
[2023-07-17 00:28:51 *28.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#82 does not exists
[2023-07-17 00:28:54 *28.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#83 does not exists
[2023-07-17 00:29:05 *28.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#84 does not exists
[2023-07-17 00:29:05 *28.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#85 does not exists
[2023-07-17 00:29:07 *28.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#86 does not exists
[2023-07-17 00:29:07 *28.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#87 does not exists
[2023-07-17 00:29:07 *28.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#88 does not exists
[2023-07-17 00:29:10 *28.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#89 does not exists
[2023-07-17 00:29:16 *28.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#90 does not exists
[2023-07-17 00:29:30 *28.0]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#91 does not exists

**Comment by 0daynick** [comment]
你的提示就是redis连接不上呀。

**Comment by irol765** [comment]
但是我是在一台主机里面的呀，用的就是你的教程，一起部署的

**Comment by 0daynick** [comment]
确保 redis 和 mysql 启动完成了，可以通过 logs 相关命令自行排查问题，再去启动 gptlink 这个容器。

**Comment by 0daynick** [comment]
> 但是我是在一台主机里面的呀，用的就是你的教程，一起部署的

确保 redis 和 mysql 启动完成了，可以通过 logs 相关命令自行排查问题，再去启动 gptlink 这个容器。

**Comment by irol765** [comment]
![image](https://github.com/gptlink/gptlink/assets/34485434/d0cfc3bc-2a4e-4293-ad70-f06dfcbb9c65)

这是我的日志，没有报错的。

**Comment by 0daynick** [comment]
嗯，也有提供测试连接的相关命令，本地环境的问题可以自行尝试解决

**Comment by irol765** [comment]
可是目前两个组件都正常的情况下，就是有中断呀。大神不要关闭呀，你们能再测试下吗。

**Comment by irol765** [comment]
可是目前两个组件都正常的情况下，就是有中断呀。大神不要关闭呀，你们能再测试下吗。
